export const APP_ID = "4931517";
export const VK_AUTH_LINK = 'https://oauth.vk.com/authorize';
export const VK_LINK = "https://api.vk.com/method";
export const SCOPE = 4096;
export const ALLOWED_IDS = [245216, 53448];
export const SERVER = SERVER_URL;
export const MESSAGES_TO_LOAD = 40;
export const VERSION = "5.33";
export const SERVER_RETRY = 5000;
